### ISSUE TITLE
are both the same package?

### ISSUE THREAD

**Issue by sprklinginfo** [itsmohd/laravel-settings#1]
First, thank you for making this package!

I installed the package with the command `composer require smartisan/laravel-settings` and the latest version is 1.0.

But I also found another repo: https://github.com/iamohd-zz/laravel-settings and the latest version seems to be 2.0 which has more extended history and more activities. 

I am a little confused about whether I am using the correct package and which repo I should follow. Thanks.

**Comment by iamohdisa** [comment]
Yes, unfortunately I lost the access to my previous account and had to recreate it here.

You can remove the old dependency and reinstall this one and you should be fine.

**Comment by sprklinginfo** [comment]
thanks. I just installed with `composer require smartisan/laravel-settings` which should always install the correct/latest version of the package, right?

**Comment by iamohdisa** [comment]
yes that's right

**Comment by sprklinginfo** [comment]
cool. thanks.
