### ISSUE TITLE
Events for settings?

### ISSUE THREAD

**Issue by sprklinginfo** [itsmohd/laravel-settings#2]
Hello, I've used this package to store some settings. So far it works amazing and thank you for a great job. 

One of my setting keys is to store the company logo image file path.  I can upload the image and store/update the image path. but when the image is deleted from the UI (filament admin panel) I need to have a process to remove the image file from the storage folder. I was told that I should use a model observer (Deleting). but I don't have a Settings Model and I know this package uses a repository to interact with the database table (which I know a little). so is there a deleting event I can hook to remove the image file for a setting key?

**Comment by iamohdisa** [comment]
There are no triggered events on this package, I didn't add any yet. 

Why don't you delete the image from the admin panel whenever you are unsetting logo key? that would be easier I guess.

If it's not the case, then you can extend the database repository, then add your events, call the parent methods and finally change the config to point to your custom repository.
